version: '3.3'

services:
    php_fpm:
        build: ./Docker/php
        container_name: dividends_calculator_web
        tty: true
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html

    mariadb:
        image: mariadb
#        build: ./Docker/mysql
        container_name: dividends_calculator_db
        volumes:
            - ./Docker/data/db:/var/lib/mysql/
        environment:
            TZ: "Europe/Vilnius"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD?err}
            MYSQL_USER: ${DB_USERNAME?err}
            MYSQL_PASSWORD: ${DB_PASSWORD?err}
            MYSQL_DATABASE: ${DB_DATABASE?err}

    nginx:
        image: nginx
#        build: ./Docker/nginx
        container_name: dividends_calculator_nginx
        working_dir: /var/www/html
        restart: unless-stopped
        depends_on:
            - php_fpm
        ports:
            # localPort:dockerPort
            - "8082:80"
        volumes:
            - .:/var/www/html
            - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8083:80
        container_name: dividends_calculator_phpmyadmin
        depends_on:
            - mariadb
        environment:
            UPLOAD_LIMIT: 300M
            PMA_ARBITRARY: 1

    frontend:
        build:
            context: ./../dividends_calculator_front
            dockerfile: ./../dividends_calculator_front/Docker/Dockerfile
        container_name: dividends_calculator_frontend
        ports:
            - 3003:3000
            - 24678:24678
        volumes:
            - ./../dividends_calculator_front:/app
            - /app/node_modules
            - /app/.nuxt
        stdin_open: true
        tty: true
volumes:
    mariadb:
